name: terraform-orchestration

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  init-validate-plan:
    name: init-validate-plan
    runs-on: ubuntu-latest
    environment: "test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: terraform-azurerm-init-validate-plan
        uses: ./.github/actions/terraform-azurerm-init-validate-plan
        with:
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          resource_group_name: ${{ secrets.TF_BACKEND_AZURE_RM_RESOURCE_GROUP_NAME }}
          storage_account_name: ${{ secrets.TF_BACKEND_AZURE_RM_STORAGE_ACCOUNT_NAME }}
          container_name: ${{ secrets.TF_BACKEND_AZURE_RM_CONTAINER_NAME }}
          backend_key: ${{ secrets.TF_BACKEND_AZURE_RM_KEY }}
          plan_file_name: "terraform.tfplan"
          working_directory: "./"
          terraform_version: "1.9.5"

  #apply:
  # name: apply
  # runs-on: ubuntu-latest
  # environment: ${{ (github.event.inputs.environment == 'prod' && 'prod-apply') || github.event.inputs.environment }}
  #if:
  #run: terraform apply -auto-approve tfplan
